### ISSUE TITLE
Test out new Fitbit Custom Component

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#329]
Testing Multiple users thanks to @mf-social

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/37347960-5e1b921c-26a9-11e8-8874-6a28fe273ffc.png)

**Comment by CCOSTAN** [comment]
![image](https://user-images.githubusercontent.com/2160436/37348159-d4bf76ea-26a9-11e8-9426-ec2cf7bb6c34.png)

@mf-social - After clicking configure for (carlo), it looks like it removed the stacey card. 

Also, I think the name needs to be added to the sensor ids if possible. 

![image](https://user-images.githubusercontent.com/2160436/37348251-0a4521fc-26aa-11e8-9543-f02684e7e0fe.png)

**Comment by CCOSTAN** [comment]
This screen does not go away after pressing the button. 

![image](https://user-images.githubusercontent.com/2160436/37348863-821da072-26ab-11e8-8896-c835bfa800db.png)

**Comment by CCOSTAN** [comment]
The setup screen does not go away after clicking the button on the bottom.

**Comment by CCOSTAN** [comment]
I'm seeing this in the logs. 
```bash
Tue Mar 13 2018 10:53:22 GMT-0400 (Eastern Daylight Time)

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/static.py", line 68, in staticresource_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/real_ip.py", line 27, in real_ip_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/auth.py", line 52, in auth_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/view.py", line 97, in handle
    result = handler(request, **request.match_info)
  File "/config/custom_components/sensor/fitbit.py", line 373, in get
    save_json(config.get(CONF_FILENAME), config_contents)
NameError: name 'config' is not defined
```

**Comment by CCOSTAN** [comment]
I can't get it to work with the first one yet with the new changes.

**Comment by mf-social** [comment]
Okay, I'll have another look when I get back in front of a computer - thanks for the info so far, hopefully not too difficult to fix those.

**Comment by CCOSTAN** [comment]
No worries Mark, whenever you get a chance.. this is something that will be of great benefit in my house (we have 3 Fitbits actually) so ANY testing I can do to help you, please let me know.  This is a win-win.
