### ISSUE TITLE
Install and run HAGraph against my config

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#34]
https://github.com/happyleavesaoc/home-assistant-graph

Great way to visualize the config data and relationships.

**Comment by CCOSTAN** [comment]
I was unable to get this working. :( 

```bash
pi@Carlo-Pi:~ $ sudo python3 -m hagraph -i /home/hass/.homeassistant/configuration.yaml -o /home/hass/.homeassistant/www/graph.svg
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/hagraph/__main__.py", line 30, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/hagraph/__main__.py", line 25, in main
    graph = make_graph(conf)
  File "/usr/local/lib/python3.4/dist-packages/hagraph/__init__.py", line 236, in make_graph
    add_core_edges(conf, graph)
  File "/usr/local/lib/python3.4/dist-packages/hagraph/__init__.py", line 200, in add_core_edges
    add_script(name, data, graph)
  File "/usr/local/lib/python3.4/dist-packages/hagraph/__init__.py", line 170, in add_script
    graph.add_edge(script_entity, target, label=get_service(step))
  File "/usr/local/lib/python3.4/dist-packages/hagraph/__init__.py", line 125, in get_service
    raise ValueError('no service')
ValueError: no service
```
I also wasn't crazy that the install also upgraded my Home Assistant. :(
