### ISSUE TITLE
MPD (music player deamon) kills after speech

### ISSUE THREAD

**Issue by mbijker** [CCOSTAN/Home-AssistantConfig#350]
Hello,

First of all thank you very much for sharing your config!
I'm busy implementing your speech engine and speech prosessing scripts but I'm having a bit of trouble with is.
I'm using MPD media player in homeassistant on my raspberry pi. The script runs fine but after one run my MPD player throws an error and I have to restart my pi to fix it.
The error I'm getting is:

Log Details (ERROR)
Sat Apr 28 2018 12:14:19 GMT+0200 (West-Europa (zomertijd))

mpd: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 188, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/mpd.py", line 130, in update
    self._fetch_status()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/mpd.py", line 113, in _fetch_status
    self._currentsong = self._client.currentsong()
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 629, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 254, in _execute
    return retval()
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 623, in decorator
    return function(self, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 404, in _fetch_object
    objs = list(self._read_objects())
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 332, in _read_objects
    for key, value in self._read_pairs():
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 314, in _read_pairs
    pair = self._read_pair(separator)
  File "/srv/homeassistant/lib/python3.5/site-packages/mpd.py", line 307, in _read_pair
    raise ProtocolError("Could not parse pair: '%s'" % line)
mpd.ProtocolError: Could not parse pair: '  '

I hope you can help me?
Thanks in advance

**Comment by CCOSTAN** [comment]
@d0ugal 100%, The CCAs allow you to group them and all TTS and music will be sync'd and played back.  It's awesome.
